[project]
name = "photon-docker"
version = "1.0.0"
description = "Unofficial docker image for the Photon Geocoder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests==2.32.4",
    "tqdm==4.67.1",
]
