name: Build and Publish Docker Image
on:
    workflow_dispatch:
        inputs:
            container_version:
                description: "Container version to build (e.g., 1.2.3 or 1.2.3-beta)"
                required: true
            photon_version:
                description: "Photon version"
                required: true
            branch:
                description: "Branch to build from"
                required: true
                default: "main"
                type: choice
                options:
                    - main
                    - dev

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Determine version and tags
              id: determine_tags
              run: |
                  CONTAINER_VERSION="${{ github.event.inputs.container_version }}"
                  PHOTON_VERSION="${{ github.event.inputs.photon_version }}"

                  CONTAINER_VERSION="${CONTAINER_VERSION#v}"

                  if [[ "$CONTAINER_VERSION" == *"-beta"* ]] || [ "${{ github.event.inputs.branch }}" == "dev" ]; then
                    IS_PRERELEASE="true"
                  else
                    IS_PRERELEASE="false"
                  fi

                  echo "CONTAINER_VERSION=$CONTAINER_VERSION" >> "$GITHUB_ENV"
                  echo "PHOTON_VERSION=$PHOTON_VERSION" >> "$GITHUB_ENV"
                  echo "IS_PRERELEASE=$IS_PRERELEASE" >> "$GITHUB_ENV"

                  TAGS="rtuszik/photon-docker:$CONTAINER_VERSION"
                  TAGS="$TAGS,ghcr.io/rtuszik/photon-docker:$CONTAINER_VERSION"

                  if [ "$IS_PRERELEASE" == "true" ]; then
                    TAGS="$TAGS,rtuszik/photon-docker:beta"
                    TAGS="$TAGS,ghcr.io/rtuszik/photon-docker:beta"
                  else
                    TAGS="$TAGS,rtuszik/photon-docker:latest"
                    TAGS="$TAGS,ghcr.io/rtuszik/photon-docker:latest"
                  fi

                  echo "DOCKER_TAGS=$TAGS" >> "$GITHUB_ENV"

                  echo "Container Version: $CONTAINER_VERSION"
                  echo "Photon Version: $PHOTON_VERSION"
                  echo "Is Prerelease: $IS_PRERELEASE"
                  echo "Tags: $TAGS"

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  build-args: |
                      PHOTON_VERSION=${{ env.PHOTON_VERSION }}
                  push: true
                  tags: ${{ env.DOCKER_TAGS }}
                  platforms: linux/amd64,linux/arm64
