name: checks

on:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  enable-cache: true
                  version: 0.8.*

            - name: Install dependencies
              run: uv sync --locked

            - name: Run linting
              run: |
                  uv run ruff check --fix
                  uv run ruff format

            - name: Run type checking
              run: uv run ty check

            - name: Run vulture
              run: uv run vulture --min-confidence 100 --exclude ".venv" .
